import os
from pydub import AudioSegment
from mutagen.mp3 import MP3
from mutagen.id3 import ID3, TIT2, TPE1, COMM

def mix_stems_without_drums(stems_path, output_path, project_root="."):
    # Mix all stems except drums
    components = ["vocals", "bass", "other"]
    mixed = None
    for comp in components:
        file = os.path.join(stems_path, f"{comp}.wav")
        if os.path.exists(file):
            seg = AudioSegment.from_wav(file)
            mixed = seg if mixed is None else mixed.overlay(seg)
        else:
            print(f"⚠️  Missing stem: {comp}. Skipping.")
    if mixed:
        os.makedirs(os.path.dirname(output_path), exist_ok=True)
        mixed.export(output_path, format="mp3", bitrate="320k")
        print(f"✅ Final track saved to {output_path}")
    else:
        print("❌ No valid stems found. Cannot create mix without drums.")

def set_mp3_metadata(mp3_path, info):
    """Set title, artist, and comment metadata on an MP3 file using mutagen."""
    if info is None:
        return
    try:
        audio = MP3(mp3_path, ID3=ID3)
        if audio.tags is None:
            audio.add_tags()
        # Try to extract artist and title from info dict
        title = info.get("track") or info.get("title") or ""
        artist = info.get("artist") or info.get("uploader") or info.get("channel") or ""
        # If title contains ' - ', split to get artist and title
        if not artist and ' - ' in title:
            artist, title = title.split(' - ', 1)
        # Set tags
        pretty_title = f"{title.strip()} (Drumless)" if title else "Drumless Version"
        audio.tags.add(TIT2(encoding=3, text=pretty_title))
        if artist:
            audio.tags.add(TPE1(encoding=3, text=artist.strip()))
        audio.tags.add(COMM(encoding=3, lang="eng", desc="", text="Drumless version generated by SCNet"))
        audio.save()
        print(f"✅ Metadata set: Title='{pretty_title}', Artist='{artist.strip() if artist else ''}'")
    except Exception as e:
        print(f"⚠️  Could not set metadata: {e}")
